// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "monster":
            case "anim1":return [img`
........................
........................
........................
........................
..........ffff..........
........ff2222ff........
.......fb222222bf.......
.......f22222222f.......
......f4222222224f......
......f4222222224f......
......f4442222444f......
......fb4bf55fb4bf......
......fc4cf22fc4cf......
.......fb222222bf.......
......fffc4b2b4ffff.....
....fc222cbfbfc222cf....
....f2b2b2ffff2b2b2f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
